using Microsoft.AspNetCore.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using O2morny.Domain.Common.Entities;

namespace O2morny.Infrastructure.Persistence.Seed
{
    public static class SeedCities
    {
        public static async Task SeedCitiesAsync(this WebApplication app, CancellationToken ct)
        {
            using var scope = app.Services.CreateScope();

            var context = scope.ServiceProvider.GetRequiredService<O2mornyContext>();

            if (await context.Cities.AnyAsync())
                return;

            var cities = new List<City> {
                new() { ArName = "القاهرة", EnName = "Cairo", CountryId = 1 },
                new() { ArName = "الجيزة", EnName = "Giza", CountryId = 1 },
                new() { ArName = "الإسكندرية", EnName = "Alexandria", CountryId = 1 },
                new() { ArName = "الدقهلية", EnName = "Dakahlia", CountryId = 1 },
                new() { ArName = "البحر الأحمر", EnName = "Red Sea", CountryId = 1 },
                new() { ArName = "البحيرة", EnName = "Beheira", CountryId = 1 },
                new() { ArName = "الفيوم", EnName = "Fayoum", CountryId = 1 },
                new() { ArName = "الغربية", EnName = "Gharbia", CountryId = 1 },
                new() { ArName = "الإسماعيلية", EnName = "Ismailia", CountryId = 1 },
                new() { ArName = "المنوفية", EnName = "Menofia", CountryId = 1 },
                new() { ArName = "المنيا", EnName = "Minya", CountryId = 1 },
                new() { ArName = "القليوبية", EnName = "Qaliubiya", CountryId = 1 },
                new() { ArName = "الوادي الجديد", EnName = "New Valley", CountryId = 1 },
                new() { ArName = "السويس", EnName = "Suez", CountryId = 1 },
                new() { ArName = "أسوان", EnName = "Aswan", CountryId = 1 },
                new() { ArName = "أسيوط", EnName = "Assiut", CountryId = 1 },
                new() { ArName = "بني سويف", EnName = "Beni Suef", CountryId = 1 },
                new() { ArName = "بورسعيد", EnName = "Port Said", CountryId = 1 },
                new() { ArName = "دمياط", EnName = "Damietta", CountryId = 1 },
                new() { ArName = "الشرقية", EnName = "Sharkia", CountryId = 1 },
                new() { ArName = "جنوب سيناء", EnName = "South Sinai", CountryId = 1 },
                new() { ArName = "كفر الشيخ", EnName = "Kafr El Sheikh", CountryId = 1 },
                new() { ArName = "مطروح", EnName = "Matrouh", CountryId = 1 },
                new() { ArName = "الأقصر", EnName = "Luxor", CountryId = 1 },
                new() { ArName = "قنا", EnName = "Qena", CountryId = 1 },
                new() { ArName = "شمال سيناء", EnName = "North Sinai", CountryId = 1 },
                new() { ArName = "سوهاج", EnName = "Sohag", CountryId = 1 },
                new() { ArName = "الرياض", EnName = "Riyadh", CountryId = 2 },
                new() { ArName = "جدة", EnName = "Jeddah", CountryId = 2 },
                new() { ArName = "مكة المكرمة", EnName = "Makkah", CountryId = 2 },
                new() { ArName = "المدينة المنورة", EnName = "Madinah", CountryId = 2 },
                new() { ArName = "الدمام", EnName = "Dammam", CountryId = 2 },
                new() { ArName = "الخبر", EnName = "Khobar", CountryId = 2 },
                new() { ArName = "الظهران", EnName = "Dhahran", CountryId = 2 },
                new() { ArName = "الطائف", EnName = "Taif", CountryId = 2 },
                new() { ArName = "بريدة", EnName = "Buraidah", CountryId = 2 },
                new() { ArName = "تبوك", EnName = "Tabuk", CountryId = 2 },
                new() { ArName = "خميس مشيط", EnName = "Khamis Mushait", CountryId = 2 },
                new() { ArName = "أبها", EnName = "Abha", CountryId = 2 },
                new() { ArName = "حائل", EnName = "Hail", CountryId = 2 },
                new() { ArName = "نجران", EnName = "Najran", CountryId = 2 },
                new() { ArName = "الجبيل", EnName = "Jubail", CountryId = 2 },
                new() { ArName = "ينبع", EnName = "Yanbu", CountryId = 2 },
                new() { ArName = "القطيف", EnName = "Qatif", CountryId = 2 },
                new() { ArName = "الأحساء", EnName = "Al-Ahsa", CountryId = 2 },
                new() { ArName = "جازان", EnName = "Jazan", CountryId = 2 },
                new() { ArName = "عرعر", EnName = "Arar", CountryId = 2 },
                new() { ArName = "سكاكا", EnName = "Sakaka", CountryId = 2 },
                new() { ArName = "الباحة", EnName = "Al-Baha", CountryId = 2 },
                new() { ArName = "بيشة", EnName = "Bisha", CountryId = 2 },
                new() { ArName = "رابغ", EnName = "Rabigh", CountryId = 2 },
                new() { ArName = "القريات", EnName = "Al-Qurayyat", CountryId = 2 },
                new() { ArName = "الخرج", EnName = "Al-Kharj", CountryId = 2 },
                new() { ArName = "القنفذة", EnName = "Al-Qunfudhah", CountryId = 2 },
                new() { ArName = "الليث", EnName = "Al-Lith", CountryId = 2 },
                new() { ArName = "المجمعة", EnName = "Al-Majma'ah", CountryId = 2 },
                new() { ArName = "عنيزة", EnName = "Unaizah", CountryId = 2 },
                new() { ArName = "الرس", EnName = "Ar Rass", CountryId = 2 },
                new() { ArName = "وادي الدواسر", EnName = "Wadi Al-Dawasir", CountryId = 2 },
                new() { ArName = "أبوظبي", EnName = "Abu Dhabi", CountryId = 3 },
                new() { ArName = "دبي", EnName = "Dubai", CountryId = 3 },
                new() { ArName = "الشارقة", EnName = "Sharjah", CountryId = 3 },
                new() { ArName = "عجمان", EnName = "Ajman", CountryId = 3 },
                new() { ArName = "أم القيوين", EnName = "Umm Al Quwain", CountryId = 3 },
                new() { ArName = "رأس الخيمة", EnName = "Ras Al Khaimah", CountryId = 3 },
                new() { ArName = "الفجيرة", EnName = "Fujairah", CountryId = 3 },
                new() { ArName = "العين", EnName = "Al Ain", CountryId = 3 },
                new() { ArName = "خورفكان", EnName = "Khor Fakkan", CountryId = 3 },
                new() { ArName = "دبا الفجيرة", EnName = "Dibba Al-Fujairah", CountryId = 3 },
                new() { ArName = "الرويس", EnName = "Ruwais", CountryId = 3 },
                new() { ArName = "ليوا", EnName = "Liwa", CountryId = 3 },
                new() { ArName = "مدينة الكويت", EnName = "Kuwait City", CountryId = 4 },
                new() { ArName = "حولي", EnName = "Hawally", CountryId = 4 },
                new() { ArName = "السالمية", EnName = "Salmiya", CountryId = 4 },
                new() { ArName = "الفروانية", EnName = "Farwaniya", CountryId = 4 },
                new() { ArName = "الجهراء", EnName = "Jahra", CountryId = 4 },
                new() { ArName = "الأحمدي", EnName = "Al Ahmadi", CountryId = 4 },
                new() { ArName = "مبارك الكبير", EnName = "Mubarak Al-Kabeer", CountryId = 4 },
                new() { ArName = "الفحيحيل", EnName = "Fahaheel", CountryId = 4 },
                new() { ArName = "الدوحة", EnName = "Doha", CountryId = 5 },
                new() { ArName = "الريان", EnName = "Al Rayyan", CountryId = 5 },
                new() { ArName = "الوكرة", EnName = "Al Wakrah", CountryId = 5 },
                new() { ArName = "الخور", EnName = "Al Khor", CountryId = 5 },
                new() { ArName = "أم صلال", EnName = "Umm Salal", CountryId = 5 },
                new() { ArName = "الشحانية", EnName = "Al Shahaniya", CountryId = 5 },
                new() { ArName = "مسيعيد", EnName = "Mesaieed", CountryId = 5 },
                new() { ArName = "دخان", EnName = "Dukhan", CountryId = 5 },
                new() { ArName = "المنامة", EnName = "Manama", CountryId = 6 },
                new() { ArName = "المحرق", EnName = "Muharraq", CountryId = 6 },
                new() { ArName = "الرفاع", EnName = "Riffa", CountryId = 6 },
                new() { ArName = "مدينة حمد", EnName = "Hamad Town", CountryId = 6 },
                new() { ArName = "مدينة عيسى", EnName = "Isa Town", CountryId = 6 },
                new() { ArName = "سترة", EnName = "Sitra", CountryId = 6 },
                new() { ArName = "جد حفص", EnName = "Jidhafs", CountryId = 6 },
                new() { ArName = "البديع", EnName = "Budaiya", CountryId = 6 },
                new() { ArName = "مسقط", EnName = "Muscat", CountryId = 7 },
                new() { ArName = "صلالة", EnName = "Salalah", CountryId = 7 },
                new() { ArName = "صحار", EnName = "Sohar", CountryId = 7 },
                new() { ArName = "نزوى", EnName = "Nizwa", CountryId = 7 },
                new() { ArName = "صور", EnName = "Sur", CountryId = 7 },
                new() { ArName = "الرستاق", EnName = "Rustaq", CountryId = 7 },
                new() { ArName = "عبري", EnName = "Ibri", CountryId = 7 },
                new() { ArName = "البريمي", EnName = "Al Buraimi", CountryId = 7 },
                new() { ArName = "خصب", EnName = "Khasab", CountryId = 7 },
                new() { ArName = "الدقم", EnName = "Duqm", CountryId = 7 },
                new() { ArName = "صنعاء", EnName = "Sanaa", CountryId = 8 },
                new() { ArName = "عدن", EnName = "Aden", CountryId = 8 },
                new() { ArName = "تعز", EnName = "Taiz", CountryId = 8 },
                new() { ArName = "الحديدة", EnName = "Hodeidah", CountryId = 8 },
                new() { ArName = "إب", EnName = "Ibb", CountryId = 8 },
                new() { ArName = "المكلا", EnName = "Mukalla", CountryId = 8 },
                new() { ArName = "ذمار", EnName = "Dhamar", CountryId = 8 },
                new() { ArName = "سيئون", EnName = "Sayun", CountryId = 8 },
                new() { ArName = "مأرب", EnName = "Marib", CountryId = 8 },
                new() { ArName = "زبيد", EnName = "Zabid", CountryId = 8 },
                new() { ArName = "عمان", EnName = "Amman", CountryId = 9 },
                new() { ArName = "الزرقاء", EnName = "Zarqa", CountryId = 9 },
                new() { ArName = "إربد", EnName = "Irbid", CountryId = 9 },
                new() { ArName = "العقبة", EnName = "Aqaba", CountryId = 9 },
                new() { ArName = "السلط", EnName = "Salt", CountryId = 9 },
                new() { ArName = "مادبا", EnName = "Madaba", CountryId = 9 },
                new() { ArName = "الكرك", EnName = "Karak", CountryId = 9 },
                new() { ArName = "جرش", EnName = "Jerash", CountryId = 9 },
                new() { ArName = "المفرق", EnName = "Mafraq", CountryId = 9 },
                new() { ArName = "معان", EnName = "Ma'an", CountryId = 9 },
                new() { ArName = "الطفيلة", EnName = "Tafilah", CountryId = 9 },
                new() { ArName = "عجلون", EnName = "Ajloun", CountryId = 9 },
                new() { ArName = "بيروت", EnName = "Beirut", CountryId = 10 },
                new() { ArName = "طرابلس", EnName = "Tripoli", CountryId = 10 },
                new() { ArName = "صيدا", EnName = "Sidon", CountryId = 10 },
                new() { ArName = "صور", EnName = "Tyre", CountryId = 10 },
                new() { ArName = "زحلة", EnName = "Zahle", CountryId = 10 },
                new() { ArName = "جونية", EnName = "Jounieh", CountryId = 10 },
                new() { ArName = "بعلبك", EnName = "Baalbek", CountryId = 10 },
                new() { ArName = "النبطية", EnName = "Nabatieh", CountryId = 10 },
                new() { ArName = "جبيل", EnName = "Byblos", CountryId = 10 },
                new() { ArName = "طرابلس الشام", EnName = "Batroun", CountryId = 10 },
                new() { ArName = "دمشق", EnName = "Damascus", CountryId = 11 },
                new() { ArName = "حلب", EnName = "Aleppo", CountryId = 11 },
                new() { ArName = "حمص", EnName = "Homs", CountryId = 11 },
                new() { ArName = "اللاذقية", EnName = "Latakia", CountryId = 11 },
                new() { ArName = "حماة", EnName = "Hama", CountryId = 11 },
                new() { ArName = "دير الزور", EnName = "Deir ez-Zor", CountryId = 11 },
                new() { ArName = "الرقة", EnName = "Raqqa", CountryId = 11 },
                new() { ArName = "طرطوس", EnName = "Tartus", CountryId = 11 },
                new() { ArName = "إدلب", EnName = "Idlib", CountryId = 11 },
                new() { ArName = "درعا", EnName = "Daraa", CountryId = 11 },
                new() { ArName = "السويداء", EnName = "As-Suwayda", CountryId = 11 },
                new() { ArName = "القامشلي", EnName = "Qamishli", CountryId = 11 },
                new() { ArName = "بغداد", EnName = "Baghdad", CountryId = 12 },
                new() { ArName = "البصرة", EnName = "Basra", CountryId = 12 },
                new() { ArName = "الموصل", EnName = "Mosul", CountryId = 12 },
                new() { ArName = "أربيل", EnName = "Erbil", CountryId = 12 },
                new() { ArName = "النجف", EnName = "Najaf", CountryId = 12 },
                new() { ArName = "كربلاء", EnName = "Karbala", CountryId = 12 },
                new() { ArName = "كركوك", EnName = "Kirkuk", CountryId = 12 },
                new() { ArName = "السليمانية", EnName = "Sulaymaniyah", CountryId = 12 },
                new() { ArName = "الناصرية", EnName = "Nasiriyah", CountryId = 12 },
                new() { ArName = "الرمادي", EnName = "Ramadi", CountryId = 12 },
                new() { ArName = "الفلوجة", EnName = "Fallujah", CountryId = 12 },
                new() { ArName = "تكريت", EnName = "Tikrit", CountryId = 12 },
                new() { ArName = "العمارة", EnName = "Amarah", CountryId = 12 },
                new() { ArName = "الديوانية", EnName = "Diwaniyah", CountryId = 12 },
                new() { ArName = "القدس", EnName = "Jerusalem", CountryId = 13 },
                new() { ArName = "غزة", EnName = "Gaza", CountryId = 13 },
                new() { ArName = "رام الله", EnName = "Ramallah", CountryId = 13 },
                new() { ArName = "الخليل", EnName = "Hebron", CountryId = 13 },
                new() { ArName = "نابلس", EnName = "Nablus", CountryId = 13 },
                new() { ArName = "بيت لحم", EnName = "Bethlehem", CountryId = 13 },
                new() { ArName = "جنين", EnName = "Jenin", CountryId = 13 },
                new() { ArName = "طولكرم", EnName = "Tulkarm", CountryId = 13 },
                new() { ArName = "قلقيلية", EnName = "Qalqilya", CountryId = 13 },
                new() { ArName = "أريحا", EnName = "Jericho", CountryId = 13 },
                new() { ArName = "خان يونس", EnName = "Khan Yunis", CountryId = 13 },
                new() { ArName = "رفح", EnName = "Rafah", CountryId = 13 },
                new() { ArName = "طرابلس", EnName = "Tripoli", CountryId = 14 },
                new() { ArName = "بنغازي", EnName = "Benghazi", CountryId = 14 },
                new() { ArName = "مصراتة", EnName = "Misrata", CountryId = 14 },
                new() { ArName = "الزاوية", EnName = "Zawiya", CountryId = 14 },
                new() { ArName = "البيضاء", EnName = "Bayda", CountryId = 14 },
                new() { ArName = "زليتن", EnName = "Zliten", CountryId = 14 },
                new() { ArName = "أجدابيا", EnName = "Ajdabiya", CountryId = 14 },
                new() { ArName = "سبها", EnName = "Sabha", CountryId = 14 },
                new() { ArName = "درنة", EnName = "Derna", CountryId = 14 },
                new() { ArName = "طبرق", EnName = "Tobruk", CountryId = 14 },
                new() { ArName = "تونس", EnName = "Tunis", CountryId = 15 },
                new() { ArName = "صفاقس", EnName = "Sfax", CountryId = 15 },
                new() { ArName = "سوسة", EnName = "Sousse", CountryId = 15 },
                new() { ArName = "القيروان", EnName = "Kairouan", CountryId = 15 },
                new() { ArName = "بنزرت", EnName = "Bizerte", CountryId = 15 },
                new() { ArName = "قابس", EnName = "Gabes", CountryId = 15 },
                new() { ArName = "أريانة", EnName = "Ariana", CountryId = 15 },
                new() { ArName = "قفصة", EnName = "Gafsa", CountryId = 15 },
                new() { ArName = "المنستير", EnName = "Monastir", CountryId = 15 },
                new() { ArName = "نابل", EnName = "Nabeul", CountryId = 15 },
                new() { ArName = "الجزائر العاصمة", EnName = "Algiers", CountryId = 16 },
                new() { ArName = "وهران", EnName = "Oran", CountryId = 16 },
                new() { ArName = "قسنطينة", EnName = "Constantine", CountryId = 16 },
                new() { ArName = "عنابة", EnName = "Annaba", CountryId = 16 },
                new() { ArName = "باتنة", EnName = "Batna", CountryId = 16 },
                new() { ArName = "سطيف", EnName = "Setif", CountryId = 16 },
                new() { ArName = "سيدي بلعباس", EnName = "Sidi Bel Abbes", CountryId = 16 },
                new() { ArName = "بسكرة", EnName = "Biskra", CountryId = 16 },
                new() { ArName = "تلمسان", EnName = "Tlemcen", CountryId = 16 },
                new() { ArName = "بجاية", EnName = "Bejaia", CountryId = 16 },
                new() { ArName = "تيزي وزو", EnName = "Tizi Ouzou", CountryId = 16 },
                new() { ArName = "ورقلة", EnName = "Ouargla", CountryId = 16 },
                new() { ArName = "الرباط", EnName = "Rabat", CountryId = 17 },
                new() { ArName = "الدار البيضاء", EnName = "Casablanca", CountryId = 17 },
                new() { ArName = "فاس", EnName = "Fez", CountryId = 17 },
                new() { ArName = "مراكش", EnName = "Marrakech", CountryId = 17 },
                new() { ArName = "طنجة", EnName = "Tangier", CountryId = 17 },
                new() { ArName = "أكادير", EnName = "Agadir", CountryId = 17 },
                new() { ArName = "مكناس", EnName = "Meknes", CountryId = 17 },
                new() { ArName = "وجدة", EnName = "Oujda", CountryId = 17 },
                new() { ArName = "القنيطرة", EnName = "Kenitra", CountryId = 17 },
                new() { ArName = "تطوان", EnName = "Tetouan", CountryId = 17 },
                new() { ArName = "آسفي", EnName = "Safi", CountryId = 17 },
                new() { ArName = "الجديدة", EnName = "El Jadida", CountryId = 17 },
                new() { ArName = "نواكشوط", EnName = "Nouakchott", CountryId = 18 },
                new() { ArName = "نواذيبو", EnName = "Nouadhibou", CountryId = 18 },
                new() { ArName = "كيفة", EnName = "Kiffa", CountryId = 18 },
                new() { ArName = "روصو", EnName = "Rosso", CountryId = 18 },
                new() { ArName = "ازويرات", EnName = "Zouerate", CountryId = 18 },
                new() { ArName = "أطار", EnName = "Atar", CountryId = 18 },
                new() { ArName = "العيون", EnName = "El Ayoun", CountryId = 18 },
                new() { ArName = "كيهيدي", EnName = "Kaedi", CountryId = 18 },
                new() { ArName = "الخرطوم", EnName = "Khartoum", CountryId = 19 },
                new() { ArName = "أم درمان", EnName = "Omdurman", CountryId = 19 },
                new() { ArName = "بورتسودان", EnName = "Port Sudan", CountryId = 19 },
                new() { ArName = "كسلا", EnName = "Kassala", CountryId = 19 },
                new() { ArName = "الأبيض", EnName = "El Obeid", CountryId = 19 },
                new() { ArName = "نيالا", EnName = "Nyala", CountryId = 19 },
                new() { ArName = "الفاشر", EnName = "El Fasher", CountryId = 19 },
                new() { ArName = "مدني", EnName = "Wad Madani", CountryId = 19 },
                new() { ArName = "عطبرة", EnName = "Atbara", CountryId = 19 },
                new() { ArName = "دنقلا", EnName = "Dongola", CountryId = 19 },
                new() { ArName = "مقديشو", EnName = "Mogadishu", CountryId = 20 },
                new() { ArName = "هرجيسا", EnName = "Hargeisa", CountryId = 20 },
                new() { ArName = "بوصاصو", EnName = "Bosaso", CountryId = 20 },
                new() { ArName = "كسمايو", EnName = "Kismayo", CountryId = 20 },
                new() { ArName = "مركا", EnName = "Merca", CountryId = 20 },
                new() { ArName = "بيدوا", EnName = "Baidoa", CountryId = 20 },
                new() { ArName = "غالكايو", EnName = "Galkayo", CountryId = 20 },
                new() { ArName = "بربرة", EnName = "Berbera", CountryId = 20 },
                new() { ArName = "مدينة جيبوتي", EnName = "Djibouti City", CountryId = 21 },
                new() { ArName = "علي صبيح", EnName = "Ali Sabieh", CountryId = 21 },
                new() { ArName = "تادجورة", EnName = "Tadjourah", CountryId = 21 },
                new() { ArName = "أوبوك", EnName = "Obock", CountryId = 21 },
                new() { ArName = "ديخيل", EnName = "Dikhil", CountryId = 21 },
                new() { ArName = "أرتا", EnName = "Arta", CountryId = 21 },
                new() { ArName = "موروني", EnName = "Moroni", CountryId = 22 },
                new() { ArName = "موتسامودو", EnName = "Mutsamudu", CountryId = 22 },
                new() { ArName = "فومبوني", EnName = "Fomboni", CountryId = 22 },
                new() { ArName = "دوموني", EnName = "Domoni", CountryId = 22 },
                new() { ArName = "ميتسودجي", EnName = "Mitsoudje", CountryId = 22 },
            };

            await context.Cities.AddRangeAsync(cities, ct);

            await context.SaveChangesAsync(ct);
        }
    }
}
